#!/usr/bin/env bash

if [ "$SPIN" ]; then
    # Install LSP's
    sudo npm install typescript-language-server
    sudo pip3 install python-language-server
else
    pip install python-language-server
fi

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/plugin

ln -sf ~/dotfiles/tmux ~/tmux
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/Xresources ~/.Xresources

# link wholesale
for f in `find . \( -name "*.vim" -o -name "*.lua" \)`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/$f ~/.config/nvim/$f
done

# zsh setup
if test -d ~/.oh-my-zsh; then
    rm -rf ~/.oh-my-zsh
fi
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

for f in `find . \( -name "*.zsh" \)`; do
    ln -sf ~/dotfiles/$f ~/.oh-my-zsh/$f
done

mkdir -p $HOME/.oh-my-zsh/custom/themes
mkdir -p $HOME/.oh-my-zsh/custom/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k --depth=1

git config --global core.editor nvim
git config --global user.name 'Chad Cole'

nvim --headless +PluginInstall +qa
