#!/usr/bin/env zsh

ln -sf ~/dotfiles/terminal/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/terminal/zshrc ~/.zshrc

if [ ! -d "~/.tmux/plugins/tpm" ] ; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# Neovim
echo
echo '> Configuring Neovim'
if [ ! $SPIN ]; then
    brew install --HEAD neovim
fi

ln -fs ~/dotfiles/nvim ~/.config/nvim

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# zsh setup
echo
echo '> Configuring oh-my-zsh'
if test -d ~/.oh-my-zsh; then
    rm -rf ~/.oh-my-zsh
fi
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

mkdir -p $HOME/.oh-my-zsh/custom
cp -r ~/dotfiles/terminal/custom/* ~/.oh-my-zsh/custom/

mkdir -p $HOME/.oh-my-zsh/custom/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

mkdir -p $HOME/.oh-my-zsh/custom/themes
git clone https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k --depth=1

source $ZSH/oh-my-zsh.sh

echo
echo '> Configuring git'
git config --global core.editor nvim
git config --global user.name 'Chad Cole'

echo
echo '> Finalizing 🔍'
source ~/.zshrc
tmux source ~/.tmux.conf &

echo
echo 'Done ✅'
echo
